import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import "@/styles/globals.css";
import Asidebar from "@/components/sidebar";
import NavbarPage from "@/components/navbar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "WebCom2",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<main className="flex flex-col w-full">
					<div>
						<NavbarPage/>
					</div>
					<div className="lg:mx-25 md:mx-15 sm:mx-10 mx-5 my-20 ">
						<TooltipProvider>{children}</TooltipProvider>
					</div>
				</main>
			</body>
		</html>
	);
}
